name: hot_card
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.5+29

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_cache_manager: ^3.3.1
  awesome_dialog: ^3.1.0
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  change_app_package_name: ^1.1.0
  connectivity_plus: ^5.0.2
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  firebase_analytics: 
  firebase_auth: 
  firebase_core: 
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  webview_flutter: ^3.0.4
  flutter_facebook_auth: ^5.0.11
  flutter_holo_date_picker: ^1.1.0
  flutter_inappwebview: ^5.7.2+3
  flutter_isolate: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.4
  flutter_slidable: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  # flutter_widget_from_html: ^0.10.1
  fluttertoast: ^8.2.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_sign_in: ^6.1.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.1
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  lottie: 
  material_design_icons_flutter: ^7.0.7296
  modal_bottom_sheet: ^2.1.0
  money_formatter: ^0.0.3
  new_version: ^0.3.1
  onesignal_flutter: ^3.2.8
  pagination_view: ^2.0.0
  path: ^1.7.0
  path_provider: ^2.0.1
  pin_code_fields: ^7.4.0
  pinput: ^2.2.11
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  ribbon_widget: ^1.0.5
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  store_redirect: ^2.0.1
  syncfusion_flutter_pdfviewer:
  timelines: ^0.1.0
  url_launcher: ^6.0.3
  photo_view: ^0.14.0
  video_player: ^2.4.6
  chewie: ^1.3.5
  youtube_player_flutter: ^8.1.0

  another_flushbar: ^1.12.29
  qr_flutter: ^4.0.0
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  flutter_custom_clippers: ^2.1.0
  flutter_painter: ^1.0.1
  blobs: ^2.0.0
  flutter_webview_plugin: ^0.4.0
  intl_phone_number_input: ^0.7.3+1
  email_validator: ^2.1.17
  device_info_plus: ^8.2.2

dependency_overrides:
  package_info_plus: ^4.0.1

  
dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/details/
    - assets/icons/track_order/
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins LightItalic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
    - family: bpg
      fonts:
        - asset: assets/fonts/bpg_arial_geo.ttf
    - family: metro-bold
      fonts:
        - asset: assets/fonts/metropolis_bold.otf
    - family: metro-reg
      fonts:
        - asset: assets/fonts/metropolis_regular.otf
